---
# handlers file for wireguard

- name: restart networking
  systemd:
    name: networking
    state: restarted
  async: 120
  poll: 0
  register: net_restarting

- name: check restart networking status
  async_status:
    jid: "{{ net_restarting.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  listen: restart networking
